if (ANDROID)
    set(CONAN_PROFILE ${CMAKE_SOURCE_DIR}/conan_profiles/android-arm64)
endif()
if (LINUX)
    set(CONAN_PROFILE ${CMAKE_SOURCE_DIR}/conan_profiles/linux-gcc15)
endif ()
#message(CONAN=${CONAN_CMD})
include(${CMAKE_SOURCE_DIR}/cmake/conan_bootstrap.cmake)
find_package(nlohmann_json)

add_subdirectory(libs/core)
add_subdirectory(libs/shared_ui)
add_subdirectory(patient)